sudo: required
language: php

# See https://wordpress.org/about/requirements/ for minimum requirements; we don't go back as far as PHP 5.2 here.
php:
    - "5.6"
    - "7.2"

# WordPress versions to be tested against.
# Include the highest patch versions of the last 3 versions (including the current one), as well as master.
# When updating this, also update the "Requires at least" and "Tested up to" in README.md.
env:
    - WP_VERSION=4.7.11
    - WP_VERSION=4.8.7
    - WP_VERSION=4.9.8
    - WP_VERSION=master

# Configure our testing environment.
before_script:
    - composer install

# Run the actual tests.
script:
    - composer validate
    - vendor/bin/phpcs -s
