sudo: required
language: php

# See https://wordpress.org/about/requirements/ for minimum requirements; we don't go back as far as PHP 5.2 here.
php:
    - "5.6"
    - "7.2"

# WordPress versions to be tested against.
# Include the highest patch versions of the last 3 versions (including the current one), as well as master.
# When updating this, also update the "Requires at least" and "Tested up to" in README.md.
env:
    - WP_VERSION=4.7.11
    - WP_VERSION=4.8.7
    - WP_VERSION=4.9.8
    - WP_VERSION=master

# Clones WordPress and configures our testing environment.
before_script:
    - export PLUGIN_SLUG=$(basename $(pwd))
    - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
    - cd ..
    - mv "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - cd /tmp/wordpress
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    - cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    - composer install

# Run the actual tests.
script:
    - composer validate
    - vendor/bin/phpcs -s
